# read_methylation() against the synthetic fixture BAM
# (generated by data-raw/make_test_fixture.R).

fixture_bam = function() testthat::test_path("fixtures", "synthetic.bam")
fixture_region = "chr1:1000-7000"

read_fixture = function(...) {
  set.seed(1)
  suppressWarnings(read_methylation(fixture_bam(), fixture_region, ...))
}

test_that("read_methylation parses the fixture into a methylation_data object", {
  md = read_fixture(group_tag = "HP")
  expect_s3_class(md, "methylation_data")
  expect_gt(nrow(md$reads), 0L)
  expect_gt(nrow(md$sites), 0L)
  expect_gt(nrow(md$insertion_sites), 0L)
  expect_true(all(c("I", "D") %in% md$cigar_features$type))
  expect_true(any(is.na(md$reads$group)))
  expect_true(all(md$sites$position >= 1000L & md$sites$position <= 7000L))
})

test_that("drop_na_group combined with min_mapq/min_read_length filters the right reads", {
  # Regression: the MAPQ and read-length filters used to index full-length BAM
  # vectors against the reads table *after* drop_na_group had shortened it, so
  # the masks were misaligned (and could crash with "subscript contains NAs").
  all_reads = read_fixture(group_tag = "HP")$reads
  md = read_fixture(group_tag = "HP", drop_na_group = TRUE, min_mapq = 10,
                    min_read_length = 1000)
  expect_false(anyNA(md$reads$group))

  bam = Rsamtools::scanBam(fixture_bam(), param = Rsamtools::ScanBamParam(
    which = region_to_granges(fixture_region), what = c("qname", "mapq", "cigar"),
    tag = "HP"))[[1]]
  width = cigar_ref_width(bam$cigar)
  keep = !is.na(bam$tag$HP) & bam$mapq >= 10 & width >= 1000
  # Supplementary copies are renamed "_suppN", so compare on original qnames.
  expected = sort(bam$qname[keep])
  got = sort(sub("_supp[0-9]+$", "", md$reads$read_name))
  expect_equal(got, expected)
  expect_lt(nrow(md$reads), nrow(all_reads))
})

test_that("snv groups reads into REF/ALT by the base at the SNV", {
  # In the fixture, HP2 reads carry G at chr1:3000 (ref A).
  md = read_fixture(snv = list(position = 3000, ref = "A", alt = "G"))
  expect_equal(md$group_tag, "SNV")
  expect_identical(md$snv_position, 3000L)
  expect_setequal(unique(md$reads$group), c("REF", "ALT"))

  hp = read_fixture(group_tag = "HP")
  alt_reads = md$reads$read_name[md$reads$group == "ALT"]
  expect_true(all(hp$reads$group[match(alt_reads, hp$reads$read_name)] == "2"))
})

test_that("snv is validated", {
  expect_error(read_fixture(snv = list(position = 3000, ref = "A")), "snv")
  expect_error(read_fixture(snv = list(position = 3000, ref = "AT", alt = "G")), "snv")
  expect_error(read_fixture(snv = list(position = 3000, ref = "A", alt = "G"),
                            group_tag = "HP"), "mutually exclusive")
})
